name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - upgrade-ruby  # Run when changes are pushed to this branch

env:
  TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ACTOR: ${{ github.actor }}
  REPO: ${{ github.repository }}

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Blog with my custom Docker image
        run: |
          docker run pgpbpadilla/blog:ruby3 jekyll build

      - name: Push blog assets to branch for publishing
        run: |
          docker run -e REPO=$REPO -e ACTOR=$ACTOR -e TOKEN=$TOKEN pgpbpadilla/blog:ruby3 /blog/github.sh
        
          
