name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - upgrade-ruby  # Run when changes are pushed to this branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Blog with my custom Docker image
        run: |
          docker run pgpbpadilla/blog:ruby3 jekyll build

      - name: Push blog assets to branch for publishing
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
        run: |
          docker run -e TOKEN=${{ secrets.GITHUB_TOKEN }} pgpbpadilla/blog:ruby3 github.sh
        
          
